#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Derive the normative v1 UDB profile from the pinned ACT reference config."""

from __future__ import annotations

from pathlib import Path
import hashlib
import json
import subprocess
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
ACT_ROOT = ROOT / "third_party" / "riscv-arch-test"
EXTENSION_SOURCE = ACT_ROOT / "config" / "sail" / "sail-rv64-max" / "sail-rv64-max.yaml"
PARAM_SOURCE = ACT_ROOT / "config" / "cores" / "cvw" / "cvw-rv64gc" / "cvw-rv64gc.yaml"
OUTPUT = ROOT / "verification" / "act" / "codex-rv64-v1.yaml"
LOCK_PATH = ROOT / "config" / "dependencies.lock.json"

EXTENSIONS = {
    "I", "M", "A", "F", "D", "C",
    "Zicsr", "Zifencei", "Zicntr", "Zihpm",
    "Zba", "Zbb", "Zbs", "Zicbom",
    "Zaamo", "Zalrsc", "Zca", "Zcd",
    "U", "S", "Sm", "Sv39", "Svbare",
    "Sstc", "Svpbmt", "Svinval", "Svadu", "Sscofpmf", "Smepmp",
}


def fail(message: str) -> None:
    print(f"UDB profile generation error: {message}", file=sys.stderr)
    raise SystemExit(2)


def main() -> None:
    if not EXTENSION_SOURCE.is_file() or not PARAM_SOURCE.is_file():
        fail("pinned ACT tree is absent; fetch dependencies before regenerating")
    lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    act_lock = lock["sources"]["riscv/riscv-arch-test"]
    act_revision = act_lock["revision"]
    udb_revision = lock["sources"]["riscv-software-src/riscv-unified-db"]["revision"]
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=ACT_ROOT, check=True,
        text=True, stdout=subprocess.PIPE,
    ).stdout.strip()
    if head != act_revision:
        fail(f"ACT HEAD is {head}, expected {act_revision}")
    dirty = subprocess.run(
        ["git", "status", "--porcelain"], cwd=ACT_ROOT, check=True,
        text=True, stdout=subprocess.PIPE,
    ).stdout.strip()
    if dirty:
        fail("pinned ACT worktree is dirty")
    source_hashes = act_lock["profile_source_sha256"]
    for path in (EXTENSION_SOURCE, PARAM_SOURCE):
        relative = str(path.relative_to(ACT_ROOT))
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != source_hashes.get(relative):
            fail(f"profile source hash differs: {relative}")
    expected_pyyaml = lock["local_tools"]["pyyaml"]["version"]
    if yaml.__version__ != expected_pyyaml:
        fail(f"PyYAML is {yaml.__version__}, expected {expected_pyyaml}")

    extension_source = yaml.safe_load(EXTENSION_SOURCE.read_text(encoding="utf-8"))
    param_source = yaml.safe_load(PARAM_SOURCE.read_text(encoding="utf-8"))
    versions = {entry["name"]: entry for entry in extension_source["implemented_extensions"]}
    missing = sorted(EXTENSIONS - versions.keys())
    if missing:
        fail("reference config lacks extension(s): " + ", ".join(missing))

    params = dict(param_source["params"])
    for irrelevant in ("MUTABLE_MISA_B", "MUTABLE_MISA_Q"):
        params.pop(irrelevant, None)
    params.update({
        "PHYS_ADDR_WIDTH": 40,
        "MSTATUS_VS_LEGAL_VALUES": [0],
        "MARCHID_IMPLEMENTED": False,
        "MIMPID_IMPLEMENTED": False,
        "VENDOR_ID_BANK": 0,
        "VENDOR_ID_OFFSET": 0,
        "PMP_GRANULARITY": 2,
        "MISALIGNED_LDST": True,
        "MISALIGNED_LDST_EXCEPTION_PRIORITY": "low",
        "MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE": 4096,
        "MISALIGNED_SPLIT_STRATEGY": "sequential_bytes",
        "CACHE_BLOCK_SIZE": 64,
        "FORCE_UPGRADE_CBO_INVAL_TO_FLUSH": False,
        "M_MODE_ENDIANNESS": "little",
        "S_MODE_ENDIANNESS": "little",
        "U_MODE_ENDIANNESS": "little",
    })
    params.pop("ARCH_ID_VALUE", None)
    params.pop("IMP_ID_VALUE", None)

    profile = {
        "$schema": "config_schema.json#",
        "kind": "architecture configuration",
        "type": "fully configured",
        "name": "codex-rv64-v1",
        "description": (
            "Normative self-attested ACT selection profile for the Codex RV64 v1 hart; "
            "schema validity does not imply implementation compliance"
        ),
        "implemented_extensions": [versions[name] for name in sorted(EXTENSIONS)],
        "params": params,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(profile, sort_keys=False, width=100)
    OUTPUT.write_text(
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# Generated by scripts/generate-udb-profile.py from pinned ACT 4.0 data.\n"
        "# yaml-language-server: $schema=https://raw.githubusercontent.com/"
        f"riscv/riscv-unified-db/{udb_revision}/"
        "spec/schemas/config_schema.json\n"
        "---\n" + body,
        encoding="utf-8",
    )
    print(f"generated {OUTPUT.relative_to(ROOT)} from ACT {act_revision}")


if __name__ == "__main__":
    main()
